#!/bin/bash
dbus-send \
--system \
--dest=org.freedesktop.Hal \
--type=method_call \
--print-reply \
'/org/freedesktop/Hal/devices/computer' \
'org.freedesktop.Hal.Device.SystemPowerManagement.Shutdown'

